Name: Vedant Shirgaonkar
Roll No.: D114   
SAP ID: 60009230002

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
movies_df = pd.read_csv('/content/drive/MyDrive/RS/movies.csv')
ratings_df = pd.read_csv('/content/drive/MyDrive/RS/ratings.csv')

In [ ]:
movies_df.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
ratings_df.head(5)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
merged_df = pd.merge(ratings_df, movies_df, on='movieId')

In [ ]:
display(merged_df.head())

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
avg_rating_df = merged_df.groupby('movieId')['rating'].mean().reset_index()
avg_rating_df = avg_rating_df.rename(columns={'rating': 'avg_rating'})
print("Average Rating per Movie:")
avg_rating_df.head()

Average Rating per Movie:

   movieId  avg_rating
0        1    3.920930
1        2    3.431818
2        3    3.259615
3        4    2.357143
4        5    3.071429

In [ ]:
movies_with_ratings_df = pd.merge(movies_df, avg_rating_df, on='movieId')

print("Movies DataFrame with Average Ratings:")
display(movies_with_ratings_df.head())

Movies DataFrame with Average Ratings:

,movieId,title,genres,avg_rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143
4,5,Father of the Bride Part II (1995),Comedy,3.071429

In [ ]:
constraints = {
    'min_avg_rating': 4.0,
    'genres': ['Romance'],
    'min_release_year': 2000
}

print(f"Defined Constraints: {constraints}")

Defined Constraints: {'min_avg_rating': 4.0, 'genres': ['Romance'], 'min_release_year': 2000}

In [ ]:
constraints2 = {
    'min_avg_rating': 3.0,
    'genres': ['Comedy'],
    'min_release_year': 1995
}

print(f"Defined Constraints: {constraints}")

Defined Constraints: {'min_avg_rating': 4.0, 'genres': ['Romance'], 'min_release_year': 2000}

In [ ]:
def filter_movies(movies_data, current_constraints):
    filtered_movies = movies_data.copy()

    filtered_movies['year'] = filtered_movies['title'].str.extract(r'\((\d{4})\)', expand=False)
    filtered_movies['year'] = pd.to_numeric(filtered_movies['year'], errors='coerce')

    if 'min_release_year' in current_constraints:
        filtered_movies = filtered_movies[filtered_movies['year'] >= current_constraints['min_release_year']]

    if 'min_avg_rating' in current_constraints:
        filtered_movies = filtered_movies[filtered_movies['avg_rating'] >= current_constraints['min_avg_rating']]

    if 'genres' in current_constraints and current_constraints['genres']:
        genre_pattern = '|'.join(current_constraints['genres'])
        filtered_movies = filtered_movies[filtered_movies['genres'].str.contains(genre_pattern, case=False, na=False)]

    result_columns = ['movieId', 'title', 'genres', 'avg_rating']
    return filtered_movies[result_columns]

In [ ]:
recommended_movies = filter_movies(movies_with_ratings_df, constraints)

In [ ]:
print("Top 10 Recommended Movies Based on Constraints:")
display(recommended_movies.head(10))

Top 10 Recommended Movies Based on Constraints:

,movieId,title,genres,avg_rating
2503,3353,"Closer You Get, The (2000)",Comedy|Romance,4.500000
2661,3567,Bossa Nova (2000),Comedy|Drama|Romance,5.000000
2897,3888,Skipped Parts (2000),Drama|Romance,4.000000
2967,3983,You Can Count on Me (2000),Drama|Romance,4.166667
3083,4144,In the Mood For Love (Fa yeung nin wa) (2000),Drama|Romance,4.214286
3085,4147,Nico and Dani (Krámpack) (2000),Comedy|Drama|Romance,4.000000
3093,4157,"Price of Milk, The (2000)",Comedy|Drama|Fantasy|Romance,4.500000
3096,4160,"Widow of St. Pierre, The (Veuve de Saint-Pierr...",Drama|Romance,4.125000
3190,4307,"Fast Food, Fast Women (2000)",Comedy|Romance,4.500000
3210,4342,Big Eden (2000),Drama|Romance,4.500000